name: road_extraction_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - opencv
  - pillow
  - albumentations=1.4.11
  - tensorflow=2.16.2
  - keras=3.4.1
  - h5py
  - tqdm
  - ipykernel
  - pip:
    - segmentation-models
